### PR TITLE
Install and use LUFA directly through Arduino Board Manager

### PR DESCRIPTION
**Pull request by CrazyRedMachine**
This is the work refered to in issue https://github.com/Palatis/Arduino-Lufa/issues/22 

With this it is now possible to install LUFA directly through the Arduino IDE board manager.

In order to do so, we need to create releases from the github menu each time we want to push an update, and then edit the package_arduino-lufa_index.json to add a new entry with the new filename, url, size and hash each time we make a new release.

### Important note

when this PR is merged, we have to create an 1.0 release for it to work (package index.json is already referencing an hypothetical 1.0 release, with current contents hash and size). If no changes to the included files are needed, it will work as is, else we also need to update the index.json to reflect the new hash and filesize

### Additional Comments

- Former repository root with the library files is now found in the `libraries/Arduino-LUFA` subfolder (with this it is not necessary to install the library anymore, it is automatically included with the new boards, thanks @iFreilicht )

- LUFA files are not within a submodule anymore: they are copied and hosted directly on this repo (this is necessary so that github releases include them)

- All commits up to 4f54b19 are from the other PR https://github.com/Palatis/Arduino-Lufa/pull/21

### CODE REVIEW

**Comment by iFreilicht** [comment]
Hey @CrazyRedMachine! I know it’s been a while, but I finally became a contributor to this repo, so I’ll be able to merge your PR!

Did you change anything since our discussion in #22?

**Comment by CrazyRedMachine** [comment]
hi, this is great news :) nothing has changed on my end, this pr can be merged as is, but you'll still need to prepare a release and edit the index.json as the included hash is not correct iirc

**Comment by Palatis** [comment]
i dunno, recent Arduino IDE and framework has been so different since I work on this little project.
I'll just merge this, and if it doesn't work on newer framework just go the old fashion way.

**Comment by CrazyRedMachine** [comment]
thank you very much for the merge :) unfortunately you cannot just merge as is, you have to create a new release as well.. i prepared the package.json as if it had a 1.0 release but i don't have the rights to make a release on your repo.

you should make a 1.0 release then double check that the url/filename/size/hash match in
https://github.com/Palatis/Arduino-Lufa/blob/e5b3f2b0555a55479534db02b492a0a218a17459/package_arduino-lufa_index.json#L16

**Pull request merged**
